name: front_coach
description: "A new Flutter project."
publish_to: "none"

version: 0.1.0+0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  marionette_flutter: ^0.3.0

  front_shared:
    path: ../front_shared

  flutter_riverpod: ^2.5.1
  go_router: ^14.6.2
  freezed_annotation: ^2.4.4
  table_calendar: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.4.12
  freezed: ^2.5.7

flutter:
  uses-material-design: true
